---
title: "Untitled"
output:
  html_document:
    df_print: paged
---


```{r}
# This file will only include preprocessing of the original datasets and their respective storage

####################################################################
##  Input this file: Original covariates data set (37 columns),   ##
##   Original biomarkers(60 columns), Biomarker annotation file,  ##
##         Covariate dictionary, SNP dataset, SNP info file       ##
####################################################################

#################################################################################
##       Output from this file: Processed covariates, only with entries        ##
##          relevant to CVD[covProcessed.rds], Biomarkers dataset with         ##
##                   well labelled columns and only one entry                  ##
##                  over time (not imputed)[bioProcessed.rds],                 ##
##                     same biomarkers dataset but imputed                     ##
##          through MICE imputation[bioImputed.rds], biomarker dataset         ##
##                   with only complete cases [bioMCAR.rds],                   ##
##   biomarker preprocessed with all columns (30 columns)[bioUnfiltered.rds]   ##
#################################################################################

###########################################################################
###########################################################################
###                                                                     ###
###                         PACKAGE DECLARATION                         ###
###                                                                     ###
###########################################################################
###########################################################################


if (!require(devtools)) install.packages('devtools')
library(devtools)
if (!require(remotes)) install.packages('remotes')
library(remotes)
if (!require(ggbiplot)) install_github("vqv/ggbiplot")
library(ggbiplot)
if (!require(GGally)) install_github("GGally")
library(GGally)
if (!require(tidyverse)) install.packagaes("tidyverse")
library(tidyverse)
if (!require(naniar)) install.packages("naniar")
library(naniar)
if (!require(factoextra)) install.packages("factoextra")
library(factoextra)
if (!require(ggfortify)) install.packages("ggfortify")
library(ggfortify)
if (!require(stats)) install.packages("stats")
library(stats)
if (!require(mice)) install.packages('mice')
library(mice)
if (!require(DMwR)) install.packages('DMwR')
library(DMwR)
if (!require(impute)) BiocManager::install("impute")
library(impute)



library(parallel)
cores = detectCores()

############################################################################
############################################################################
###                                                                      ###
###                             DATA LOADING                             ###
###                                                                      ###
############################################################################
############################################################################



##################################################################
##                        Cluster add-in                        ##
##################################################################
cluster = 1
t0 = Sys.time()
platform = Sys.info()['sysname']
if (cluster == 1 & platform == "Linux"){
  cov.original = readRDS("../FULLDATA/Covariates_full.rds")
  bio.original= readRDS("../FULLDATA/Biomarkers_full.rds")
  bio.dict = readxl::read_xlsx("../Biomarker_annotation.xlsx")
  cov.dict = readxl::read_xlsx("../Covariate_dictionary.xlsx")
  snp.original = readRDS('../FULLDATA/genetic_data_cvd_snps.rds')
  snp_info.original = readxl::read_xlsx("../SNP_info.xlsx")
  
  # id's into columnss, not doing this anymore
  # rownames(bio.original) = bio.original$`mydata$eid`
  # bio.original = bio.original[,-1]
  
  # setting up ID column
  colnames(bio.original)[1] = 'ID'
  cov.original = cbind(ID = rownames(cov.original), cov.original)
  snp.original = cbind(ID = rownames(snp.original), snp.original)
  
  cov.original$ID = as.numeric(levels(cov.original$ID)[cov.original$ID])
  snp.original$ID = as.numeric(levels(snp.original$ID)[snp.original$ID])
  
  save_path = "../FULLDATA/preprocessed/"
} else {
    setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
    #################################################################
    ##                      Original datasets                      ##
    #################################################################
    cov.original = readRDS("../data/Covars_toy.rds")
    bio.original= readRDS("../data/Biomarkers_toy.rds")
    bio.dict = readxl::read_xlsx("../Biomarker_annotation.xlsx")
    cov.dict = readxl::read_xlsx("../Covariate_dictionary.xlsx")
    snp.original = readRDS('../data/Genes_toy.rds')
    snp_info.original = readxl::read_xlsx("../SNP_info.xlsx")

    bio.original = cbind(ID = 1:nrow(bio.original), bio.original)
    cov.original = cbind(ID = 1:nrow(cov.original), cov.original)
    snp.original = cbind(ID = 1:nrow(snp.original), snp.original)
    
    save_path = "../data/preprocessed/"
}



##################################################################


##################################################################
##              Changing biomarkers codes by names              ##
##################################################################
#make nicely looking names (programmingly functional)
colnames(bio.dict) = make.names(colnames(bio.dict), unique=TRUE)

#get column numbers of columns with name containing pattern *(.)1(.)*
# use (.) to match the dot as opposed to using . as a wildcard
bio = bio.original[,c(T, !grepl("*(.)1(.)0", colnames(bio.original)[-1]))]

# Match code with biomarker name to change column names of b
# get element 2 to 6 of all string in vector colnames(b)
# the match() function, match the substring from colnames to
# the UK.biobank.field in the biomarkers dictionary, 
# effectively ordering the colnames of b
# Alternative: order UK.bionbank.field entries and match them
#---- bio.dict = bio.dict %>% arrange(UK.Biobank.Field)

colnames(bio)[-1] = bio.dict$Biomarker.name[
  match(substring(colnames(bio)[-1],2,6),bio.dict$UK.Biobank.Field)] 

colnames(bio)[-1] = make.names(colnames(bio)[-1], unique=TRUE)
colnames(bio)[-1] = sub("\\.\\.",".", colnames(bio)[-1])

# safety-check for all vars being numeric
stopifnot(all(apply(bio, 2, is.numeric)))


##################################################################
##               Processing of covariates dataset               ##
##################################################################
## preprocessing c

#remove anything to do wih cancer or external deaths
cov = cov.original[,!grepl("cancer|external", colnames(cov.original))]

#remove codes except for icd10
cov = cov[,!(colnames(cov) %in% c("cvd_final_icd9",
                                  "cvd_final_nc_illness_code",
                                  "cvd_final_opcs4",
                                  "cvd_final_ukb_oper_code",
                                  "other_cause_death"))]

unfactor = function(column, df){
  #' Check if column in integer or string and  turn to the correct type
  #' to avoid other function turning into factor indices
  
  if (class(df[1,column]) == "factor"){
    if (typeof(levels(df[1,column])[df[1,column]]) == "integer"){
      out = as.numeric(levels(df[,column]))[df[,column]]
    } else if (typeof(levels(df[1,column])[df[1,column]])  == "character") {
      out = as.character(levels(df[,column]))[df[,column]]
    } else { #NA
      out = as.character(levels(df[,column]))[df[,column]]
    }
  } else {
    out = df[,column]
  }

  return(out)
}

names.cov = colnames(cov)

cov = as.data.frame(
  lapply(colnames(cov),
       function(column) {
         print(column)
       unfactor(column, cov)}), stringsAsFactors = F
  )

colnames(cov) = names.cov
```


```{r setup}
library(arsenal)
tab = tableby(CVD_status~.,
              data = select(cov, -c(cvd_final_icd10,primary_cause_death_ICD10, ID)))
knitr::kable(summary(tab))
```







